name: test-and-lint

on: push

jobs:
  check-errors:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: install
        run: make install

      - name: lint
        run: make lint

      - name: test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID : ${{ secrets.CODECLIMATE_COVERAGE_ID }}
        with:
          coverageCommand: make test-coverage
      